name: Task
description: 개발 작업 (내부용)
title: "[Task] "
labels: ["task"]
body:
  - type: textarea
    id: description
    attributes:
      label: 작업 설명
      description: 수행할 작업을 설명해주세요
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: 완료 조건
      description: 작업이 완료되었음을 확인할 수 있는 조건
      placeholder: |
        - [ ] 조건 1
        - [ ] 조건 2
    validations:
      required: false

  - type: textarea
    id: related
    attributes:
      label: 관련 이슈/PR
      description: 연관된 이슈나 PR 번호
    validations:
      required: false
